<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE work42 [
<!ELEMENT work42 (x1, x2, x3, x4)>
<!ELEMENT x1 (y1, y2?)>
<!ELEMENT x2 (y1, y2?)>
<!ELEMENT x3 (y1*, y2+)>
<!ELEMENT x4 (y1*, y2+)>
<!ELEMENT y1 EMPTY>
<!ELEMENT y2 EMPTY>
]>

<work42>
    <x1>
        <y1 />
    </x1>
    <x2>
        <y1 />
        <y2 />
    </x2>
    <x3>
        <y2 />
    </x3>
    <x4>
        <y1 />
        <y1 />
        <y2 />
    </x4>
</work42>