=== Hiroki-Imiya/kouzouka/work04/work45.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT work45 (x1, x2, x3, x4)>
<!ELEMENT x1 (a?, b+) >
<!ELEMENT x2 (a, (b*, c*)) >
<!ELEMENT x3 (a, (b, c)+) >
<!ELEMENT x4 (a | b | c)+ >
<!ELEMENT a EMPTY >
<!ELEMENT b EMPTY >
<!ELEMENT c EMPTY >

=== Hiroki-Imiya/kouzouka/work04/work45.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE work45 SYSTEM "work45.dtd">
<work45>
    <x1>
        <b />
    </x1>
    <x2>
        <a />
    </x2>
    <x3>
        <a />
        <b />
        <c />
    </x3>
    <x4>
        <c />
    </x4>
</work45>
