=== Hiroki-Imiya/kouzouka/work04/work44.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT work44 (x1, x2, x3, x4)>
<!ELEMENT x1 (a, b)+>
<!ELEMENT x2 (a+, b*)>
<!ELEMENT x3 (a+, b)*>
<!ELEMENT x4 (a|b)*>
<!ELEMENT a EMPTY>
<!ELEMENT b EMPTY>

=== Hiroki-Imiya/kouzouka/work04/work44.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE work44 SYSTEM "work44.dtd">

<work44>
    <x1>
        <a />
        <b />
        <a />
        <b />
    </x1>
    <x2>
        <a />
        <b />
        <b />
    </x2>
    <x3>
        <a />
        <a />
        <b />
    </x3>
    <x4>
        <a />
        <a />
        <a />
        <b />
    </x4>
</work44>
